name: skawa_components
version: 1.3.3
authors:
  - Harsányi Tamás (valakis) <tams.harsnyi@google.com>
  - Szepesházi András <szepeshazi@gmail.com>
  - Varga-Hali Daniel <https://github.com/daniel-v>
  - Farmasi Bulcsú <https://github.com/BulcsuFarmasi>
description:
  Additional components for AngularDart based on Material Design principles. These reusable components are not part of the official  Material Components library.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: 
    git:
      url: https://github.com/dzolotov/angular
      path: angular
      ref: master
  angular_components: 
    git:
      url: https://github.com/dzolotov/angular_components
      path: angular_components
      ref: master
  sass_builder: ^2.1.2
  markdown: ^2.0.3
  js: ^0.6.1+1
  intl: ^0.16.0
  diff_match_patch: ^0.3.0

dev_dependencies:
  html_unescape: ^1.0.1+2
  mockito: ^4.0.0
  test: ^1.6.2
  angular_test: ^2.3.0
  pageloader: ^3.2.0
  build_config: ^0.4.1+1
  build_test: ^0.10.7
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
